substitute bash features to make the script working with non-bash sh implementations
git-svn-id: https://svnsrv.desy.de/desy/mtca4u/deviceaccess/trunk@1790 5f601a5c-88b9-47f3-b851-818f6741d00d

diff --git a/cmake/PROJECT_NAME-config.in b/cmake/PROJECT_NAME-config.in
--- a/cmake/PROJECT_NAME-config.in
+++ b/cmake/PROJECT_NAME-config.in
@@ -1,15 +1,22 @@
 #!/bin/sh
 
 print_usage(){
-	echo usage: $0 [--cppflags] [--ldflags]
+    echo "usage: $0 [--cppflags] [--ldflags]" 1>&2
 }
 
-while [[ $# > 0 ]]; do
+while [ $# -gt 0 ]; do
     case "$1" in
-      --cppflags) OUTPUT+="-I@CMAKE_INSTALL_PREFIX@/include "; shift;;
-      --ldflags) OUTPUT+="-L@CMAKE_INSTALL_PREFIX@/lib -l@PROJECT_NAME@ " ; 
-	    OUTPUT+="-Wl,-rpath=@CMAKE_INSTALL_PREFIX@/lib,--enable-new-dtags "; shift;;
-      *) echo "invalid option: $1" 1>&2; print_usage; exit 1;;
+      --cppflags)
+        OUTPUT="${OUTPUT}-I@CMAKE_INSTALL_PREFIX@/include "
+        shift;;
+      --ldflags)
+        OUTPUT="${OUTPUT}-L@CMAKE_INSTALL_PREFIX@/lib -l@PROJECT_NAME@ "
+        OUTPUT="${OUTPUT}-Wl,-rpath=@CMAKE_INSTALL_PREFIX@/lib,--enable-new-dtags "
+        shift;;
+      *)
+        echo "invalid option: $1" 1>&2
+        print_usage
+        exit 1;;
     esac
 done
 
